#!/bin/bash
echo "🔍 Checking Edge Function deployment status..."
echo ""
echo "To check if the Edge Function is deployed:"
echo "1. Go to: https://app.supabase.com/project/mnsqjfwgpmyiepruifwr/functions"
echo "2. Look for 'generate-trip-plan' function"
echo ""
echo "To deploy the function:"
echo "supabase functions deploy generate-trip-plan"
echo ""
echo "To set Gemini API key:"
echo "supabase secrets set GEMINI_API_KEY=your-key-here"
echo ""
echo "To check secrets:"
echo "supabase secrets list"
