// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnsqjfwgpmyiepruifwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uc3FqZndncG15aWVwcnVpZndyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTg1NjIsImV4cCI6MjA3MzQzNDU2Mn0.xqN3JUX3f60vGLsNSSRMvVqaZyomI8N1ehrD3itIPV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});